nn:
  epochs: 2
  sample-rate: 16000
  batch:
    size: 64
    audio-length-ms: 4000

models:
  test-target: Head
  targets:
    - Head
    - Chest
    - Open
    - Breathy
    - Vibrato
    - Front
    - Back