nn:
  epochs: 10
  mel-spectrogram:
    sample-rate: 16000
    n-fft: 400
  batch:
    size: 64
    audio-length-ms: 4000

model:
  targets:
    targets:
    - Head
    - Chest
    - Open
    - Breathy
    - Vibrato
    - Front
    - Back

evaluate:
  metrics:
    metrics:
    - rmse
    - R2Score()
